config/routes.rb
Rails.application.routes.draw do
  #ユーザー関係
  devise_for :users

  #収納関係
  resources :items, onl: [:new, :create, :index, :show, :edit, :destroy, :update] do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit]
  #Topページ関係
  root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  attachment :image
#バリテーション
  validates :title, presence: true
  validates :tag, presence: true
  validates :box, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
#ログイン後の遷移先
  def after_sign_in_path_for(resource)
    items_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :search

  def search
    # params[:q]のqには検索フォームに入力した値が入る
    @q = Item.ransack(params[:q])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      flash[:notice] = '投稿に成功しました.'
      redirect_to item_path(@item.id)
    else
      @items = Item.all
      render :new
    end
  end

  def index
    @items = Item.all
    @items = @q.result(distinct: true)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user == current_user
      render "edit"
    else
      redirect_to items_path
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
    flash[:notice] = '削除に成功しました.'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item.id)
      flash[:notice] = '編集に成功しました.'
    else
      @items = Item.all
      render :edit
    end
  end

  def search
    # params[:q]のqには検索フォームに入力した値が入る
    @q = Item.ransack(params[:q])
  end

  private

  def item_params
    params.require(:item).permit(:title, :image, :explanation, :tag, :box)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxs_helper.rb
module BoxsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shelfs_helper.rb
module ShelfsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boxs/new.html.erb
<!--ユーザー側投稿ページ-->

<div class='container my-5'>
  <% if @box.errors.any? %>
    <%= @box.errors.count %>error prohibited this game from being saved:
    <% @box.errors.full_messages.each do |message| %>
      <ul class="error_explanation">
        <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>
  <div class='row mb-3'>
    <div class='col-md-3 offset-md-1'>

      <h4 class='bg-dark text-white text-center p-3'>収納作成ページ</h4>

    </div>
  </div>

  <div class='row'>
    <div class='col-md-10 offset-md-1'>

      <%= form_with model: @box, url: boxs_path(@box.id), local:true do |f| %>
      <table class='table table-borderless'>
        <!--ゲーム画像-->
        <tr>
          <div class='form-group'>
            <th>画像</th>
              <td><%= f.attachment_field :image %></td>
          </div>
        </tr>
        <!--ゲームタイトル-->
        <tr>
          <div class='form-group'>
            <th>収納場所名</th>
              <td><%= f.text_field :title, class: 'col-sm-6 form-control-static name' %></td>
          </div>
        </tr>
        <!--感想-->
        <tr>
          <div class='form-group'>
            <th>説明</th>
              <td><%= f.text_area :explanation, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>

        <tr>
          <div class='form-group'>
            <th></th>
              <td><%= f.submit '新規登録', class: 'btn btn-primary w-50' %></td>
          </div>
        </tr>

      </table>
      <% end %>
    </div>
  </div>

</div>

app/views/boxs/show.html.erb
<div>
  <%= attachment_image_tag @box, :image %>
  <p>収納棚名：<%= @box.title %></p>
  <p>説明：<%= @box.explanation %></p>
  <p>投稿日時：<%= @box.created_at.strftime('%Y/%m/%d') %></p>
  <% if @box.user == current_user %>
    <%= link_to "削除", box_path(@box), method: :delete %>
  <% end %>
</div>

app/views/homes/top.html.erb
<!--TOPページ-->
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-lg-10 mt-5 mb-5 mx-auto">
    <h2 class="col-lg-6 offset-lg-4">VirtualStorageとは</h2>
  	<div class="text_box">
	  	<p>さまざまな物を管理するサービスです。<br>
		  「どこに」「何を」しまっているのかを把握することができます。<br>
		  また、仮想の収納ゆえに宿題やタスクなどといった存在しない物も管理することができます。
		  </p>
  	</div>
    <div class="cloud_box mt-5 mx-auto">
		  <h4>日々の生活の中で、こんな困りごとありませんか？</h4>
		  <ul>
			  <li>道具や服といった物をどこに締まったか分からなくなってしまった...</li>
			  <li>本の続きが気になるのに何巻まで購入したか分からない...</li>
			  <li>家族で収納場所を共有したい...</li>
		  	<li>外出先で献立を考えたとき、家にどんな食材があるか分からないため何を買えばいいか分からない...</li>
		  	<li>課題やタスクを管理できるようにしたい...</li>
		  </ul>
	  </div>
	  <h4 class="mt-5">このサイトはそんなお悩みをすべて解決することで<br>あなたの生活の悩みを「少しでもラクに...!」をお手伝いします。</h4>
	</div>
  <div class="col-lg-10 mx-auto">
    <h2 class="subtitle">VirtualStorageのポイント</h2>
    <div>
      <div class="mt-5">
        <p>Point</p><p class="about_number">01</p>
        <div>
          <h4 class="subtitle">身の回りの道具の管理</h4>
          <p>
            読みたい本があるのに、どこに収納してしまったか分からない、今から出かけるのに、夏服が見つからない...<br>
            この様になってしまった場合、せっかくの休みの日の大事な時間を失いストレスの原因に...。<br>
            このサイトで管理することで何処にあるかを把握することができ、大事な休みの日を幸せに過ごすことができます。
          </p>
        </div>
      </div>
      <div class="about-point mt-5">
        <p>Point</p><p class="about_number">02</p>
        <div>
          <h4 class="subtitle">道具の楽々検索</h4>
          <p>
            道具の「名前」「タグ」「収納場所」のいずれかを検索することで、簡単に見つけることができ、<br>
            捜す手間を省くことができます。
          </p>
        </div>
      </div>
      <div class="about-point mt-5">
        <p>Point</p><p class="about_number">03</p>
        <div>
          <h4 class="subtitle">シンプルだから何でもできる</h4>
          <p>
            このサイトは、身の回りの道具を管理する機能とそれらを検索する機能のみのシンプルなサイトです。<br>
            それゆえに、道具の管理しか使うことができない...そんなことはありません！！<br>
            食材などといった物を管理することで、外出先でも献立を考えることができる。<br>
            タスクや宿題を管理することで、抜けをなくすことができる。<br>
            一人だけではなく、家族全員で管理できる。<br>
            このような用途の他にも様々な用途に「シンプル」ゆえに使うことができます。<br>
            このサイトは、そんなあなたの痒い所に手が届くサイトです。
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<!--収納編集ページ-->
<div class='container my-5'>
  <% if @item.errors.any? %>
    <%= @item.errors.count %>error prohibited this game from being saved:
    <% @item.errors.full_messages.each do |message| %>
      <ul class="error_explanation">
        <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>
  <div class='row mb-3'>
    <div class='col-md-3 offset-md-1'>
      <p id="notice"><%= notice %></p>
      <h4 class='bg-dark text-white text-center p-3'>編集ページ</h4>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-10 offset-md-1'>
      <%= form_with model:@item, url: item_path(@item.id), local:true do |f| %>
      <table class='table table-borderless'>
        <!--画像-->
        <tr>
          <div class='form-group'>
            <th>画像</th>
            <td><%= f.attachment_field :image %></td>
          </div>
        </tr>
        <!--タイトル-->
        <tr>
          <div class='form-group'>
            <th>タイトル</th>
              <td><%= f.text_field :title, class: 'col-sm-6 form-control-static name' %></td>
          </div>
        </tr>
        <!--収納場所-->
        <tr>
          <div class='form-group'>
            <th>収納場所</th>
              <td><%= f.text_area :box, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
        <!--タグ-->
        <tr>
          <div class='form-group'>
            <th>タグ</th>
              <td><%= f.text_area :tag, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
        <!--説明-->
        <tr>
          <div class='form-group'>
            <th>説明</th>
              <td><%= f.text_area :explanation, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
        <!--保存ボタン-->
        <tr>
          <div class='form-group'>
            <th></th>
              <td><%= f.submit '編集を保存する', class: 'btn btn-primary w-50' %></td>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<!--検索フォーム-->
<div class="">
  <%= search_form_for @q do |f| %>
  <!--title,tag,boxであいまい検索を指定-->
  <%= f.text_field :title_or_tag_or_box_cont, placeholder: '  検索ワードを入力' %>
    <%= f.submit "検索する" %>
  <% end %>
</div>
<div class='row'>
  <div class='col-md-12'>
    <!--検索結果-->
    <% if @items.present? %>
      <!--index表示-->
      <div class="list-wrap">
        <% @items.each do |item| %>
          <% if user_signed_in? && current_user.id == item.user_id %>
            <div class="list-box">
              <%= attachment_image_tag item, :image, size: '200x200', format: 'jpeg', fallback: 'NO.jpeg' %>
              <div class="list-comment">
                <!--タイトル-->
                <span class="list-title"><%=link_to item.title, item_path(item.id) %></span>
                <!--タグ-->
                <span class="list-tag"><%= item.tag %></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <!--検索がヒットしなかった場合,何も収納していない場合-->
      <p>収納されていません</p>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<!--新規収納ページ-->

<div class='container my-5'>
  <% if @item.errors.any? %>
    <%= @item.errors.count %>error prohibited this game from being saved:
    <% @item.errors.full_messages.each do |message| %>
      <ul class="error_explanation">
        <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>
  <div class='row mb-3'>
    <div class='col-md-4 offset-md-1'>
      <h4 class='bg-dark text-white text-center p-3'>新規収納</h4>
    </div>
    <p>※タイトル,収納場所,タグは、必ず入力してください</p>
  </div>

  <div class='row'>
    <div class='col-md-10 offset-md-1'>
      <%= form_with model: @item, url: items_path(@item.id), local:true do |f| %>
      <table class='table table-borderless'>
        <!--画像-->
        <tr>
          <div class='form-group'>
            <th>画像</th>
              <td><%= f.attachment_field :image %></td>
          </div>
        </tr>
        <!--タイトル-->
        <tr>
          <div class='form-group'>
            <th>タイトル</th>
              <td><%= f.text_field :title, class: 'col-sm-6 form-control-static name' %></td>
          </div>
        </tr>
        <!--収納場所-->
        <tr>
          <div class='form-group'>
            <th>収納場所</th>
              <td><%= f.text_area :box, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
　　　　<!--タグ-->
        <tr>
          <div class='form-group'>
            <th>タグ</th>
              <td><%= f.text_area :tag, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
        <!--説明-->
        <tr>
          <div class='form-group'>
            <th>説明</th>
              <td><%= f.text_area :explanation, class: 'col-sm-6 control-label introduction' %></td>
          </div>
        </tr>
        <!--追加ボタン-->
        <tr>
          <div class='form-group'>
            <th></th>
              <td><%= f.submit '新規追加', class: 'btn btn-primary w-50' %></td>
          </div>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

</div>

app/views/items/show.html.erb
<!--詳細ページ-->
<div class='container'>
  <% if @item.errors.any? %>
    <%= @item.errors.count %>error prohibited this game from being saved:
    <% @item.errors.full_messages.each do |message| %>
      <ul class="error_explanation">
        <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>
</div>
<p id="notice"><%= notice %></p>
<h1>詳細画面</h1>
<h2>タイトル</h2>
<p><%= @item.title %></p>
<h2>収納場所</h2>
<p><%= @item.box %></p>
<h2>タグ</h2>
<p><%= @item.tag %></p>
<h2>説明</h2>
<p><%= @item.explanation %></p>
<h2>投稿画像</h2>
  <%= attachment_image_tag(@item, :image, size: '900x660', fallback: 'NO.jpeg' ) %>
<!--編集,削除機能-->
<div style='border-top: none;'>
	<% if @item.user == current_user %>
		<%= link_to '編集する', edit_item_path(@item), data: {'turbolinks' => false}, class: 'glyphicon glyphicon-pencil btn btn-success pull-right edit_item_#{@item.id}' %>
	<% end %>
	<% if @item.user == current_user %>
　　　<%= link_to '削除する', item_path(@item), method: :delete, data: { confirm: '本当に消しますか？' }, class: 'glyphicon glyphicon-pencil btn btn-danger pull-right destroy_item_#{@item.id}'%>
　<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <!--ＴＯＰに戻る,サイト名-->
      <h1 class="headline">
        <a href="/">
          VirtualStorage
        </a>
      </h1>
    </header>
    <nav>
      <!--サインインしている場合-->
      <% if user_signed_in? %>
        <ul class="nav-list">
          <li class="nav-list-item">
            <%= link_to "ItemLists", items_path %>
          </li>
          <li class="nav-list-item">
            <%= link_to "New Items", new_item_path %>
          </li>
          <li class="nav-list-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
      <!--サインインしていない場合-->
        <ul class="nav-list">
          <li class="nav-list-item">
            <%= link_to "Sign_in", new_user_registration_path %>
          </li>
          <li class="nav-list-item">
            <%= link_to "Login", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>